---
- name: Copia di un file
  hosts: all
  remote_user: servermanager
  vars_files:
    - /etc/ansible/connection_password
  become: yes

  tasks:
    - name: Copia il file di configurazione 1
      copy:
        src: /var/lib/awx/projects/1/copy_file_1.yml
        dest: /root
        owner: root
        group: root
        mode: '0400'
