---
- name: Copia di un file
  hosts: all
  remote_user: servermanager
  become: yes

  tasks:
    - name: Copia il file di configurazione 1
      copy:
        src: /root/1
        dest: /root
        owner: root
        group: root
        mode: '0400'
